insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220101', 'firstName_Customer01', 'lastName_Customer01', 11, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220102', 'firstName_Customer02', 'lastName_Customer02', 12, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220103', 'firstName_Customer03', 'lastName_Customer03', 13, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220104', 'firstName_Customer04', 'lastName_Customer04', 14, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220105', 'firstName_Customer05', 'lastName_Customer05', 15, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220106', 'firstName_Customer06', 'lastName_Customer06', 16, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220107', 'firstName_Customer07', 'lastName_Customer07', 17, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220108', 'firstName_Customer08', 'lastName_Customer08', 18, CURRENT_TIMESTAMP);
insert into ADM.CUSTOMER (CUST_NO, FIRST_NAME, LAST_NAME, AGE, CREATED_AT) values ('20220109', 'firstName_Customer09', 'lastName_Customer09', 19, CURRENT_TIMESTAMP);

insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220109', 'order01', 1, CURRENT_TIMESTAMP, 'orderName01', 'ITEM111', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220109', 'order02', 2, CURRENT_TIMESTAMP, 'orderName02', 'ITEM111', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220109', 'order03', 3, CURRENT_TIMESTAMP, 'orderName03', 'ITEM111', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220109', 'order04', 2, CURRENT_TIMESTAMP, 'orderName02', 'ITEM112', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220109', 'order05', 3, CURRENT_TIMESTAMP, 'orderName03', 'ITEM112', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220110', 'order06', 4, CURRENT_TIMESTAMP, 'orderName04', 'ITEM112', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220110', 'order07', 2, CURRENT_TIMESTAMP, 'orderName02', 'ITEM112', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220110', 'order08', 3, CURRENT_TIMESTAMP, 'orderName03', 'ITEM112', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220110', 'order09', 4, CURRENT_TIMESTAMP, 'orderName04', 'ITEM112', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220111', 'order10', 3, CURRENT_TIMESTAMP, 'orderName03', 'ITEM113', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220111', 'order11', 4, CURRENT_TIMESTAMP, 'orderName04', 'ITEM113', CURRENT_TIMESTAMP);
insert into ADM.TORDER (CUST_NO, ORD_NO, ORD_SEQ, ORD_DTM, NAME, ITEM_CD, CREATED_AT) values ('20220111', 'order12', 5, CURRENT_TIMESTAMP, 'orderName05', 'ITEM113', CURRENT_TIMESTAMP);

insert into ADM.STUDENT (STD_SEQ, GRADE) values (1, '1');
insert into ADM.STUDENT (STD_SEQ, GRADE) values (2, '5');
